name: Run Unsafe Code Scan
description: Run cargo-geiger to detect unsafe Rust code
author: KiTech Software
inputs:
  no-fail:
    description: "Do not fail on unsafe code"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - run: |
        if [[ "${{ inputs.no-fail }}" == "true" ]]; then
          docker run --rm -v "$PWD":/usr/src/app -w /usr/src/app ghcr.io/kitechsoftware/gcr-rust:latest unsafe-scan --no-fail --output unsafe-code-report
        else
          docker run --rm -v "$PWD":/usr/src/app -w /usr/src/app ghcr.io/kitechsoftware/gcr-rust:latest unsafe-scan --output unsafe-code-report
        fi
      shell: bash
    - name: Upload unsafe code report
      uses: actions/upload-artifact@v4
      with:
        name: unsafe-code-report
        path: unsafe-code-report.txt
    - name: Append to GitHub Summary
      run: |
        cat unsafe-code-report.md >> "$GITHUB_STEP_SUMMARY"
      shell: bash